/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package local.ytk.g.unnamedgame1;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test void appHasAGreeting() {
    //     UnnamedGame1 classUnderTest = new UnnamedGame1();
    //     assertNotNull(classUnderTest.toString(), "app should have a greeting");
    // }
}
