/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package local.ytk.g.platformer1;

import local.ytk.g.platformer1.data.codecs.Encoder;
import local.ytk.util.Result;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
//    @Test void appHasAGreeting() {
//     Object classUnderTest = new Object();
//     assertNotNull(classUnderTest.toString(), "app should have aCodec greeting");
//    }
    
    @Test
    void x() {
        assertEquals(Result.fail().successful(), Result.fail().map(null).successful());
        assertDoesNotThrow(() -> System.out.println("A." + Encoder.of((o, a) -> o + "B." + a).encode(null, "C.", null).value()));
    }
    
}
